name: Deploy Hugo Site to S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - run: hugo --minify

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::$AWS_ACCOUNT_ID:role/$AWS_ROLE_NAME
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: $AWS_REGION

      - name: Deploy to S3
        run: aws s3 sync ./public s3://$AWS_BUCKET_NEWSLETTER --delete
